image: docker:18
stages:
- build

cache:
  paths:
  - /apt-cache
  - /go/src/github.com
  - /go/src/golang.org
  - /go/src/google.golang.org
  - /go/src/gopkg.in

before_script:
- rm -rf build/

build_prod:
  stage: build
  script:
  - docker build  -f $(pwd)/docker/Dockerfile_build -t broadcast-server-build:latest .
  - docker run -v $(pwd)/:/go/src/gitlab.zarinpal.com/zarinpal/broadcast-server broadcast-server-build:latest
  - docker build  -f $(pwd)/docker/Dockerfile -t gitlab.zarinpal.com:5555/zarinpal/broadcast-server:latest .
  - docker push gitlab.zarinpal.com:5555/zarinpal/broadcast-server:latest
  only:
  - release

build_stg:
  stage: build
  script:
  - docker build  -f docker/Dockerfile_build -t broadcast-server-build:latest .
  - docker run -v $(pwd)/:/go/src/gitlab.zarinpal.com/zarinpal/broadcast-server broadcast-server-build:latest
  - docker build  -f docker/Dockerfile -t gitlab.zarinpal.com:5555/zarinpal/broadcast-server:stg-$CI_PIPELINE_IID .
  - docker push gitlab.zarinpal.com:5555/zarinpal/broadcast-server:stg-$CI_PIPELINE_IID
  only:
  - master

